### ISSUE TITLE
find_max_value

### ISSUE THREAD

**Issue by novinxy** [Heraved/Learningpython#7]
zaimplementuj funkcję która przyjmuje listę wartosci jako argument, znajduje największą wartość w tej liscie i zwraca ją na returnie. W pythonie juz istnieje funkcja max, ktora to robi, ale chciałbym abyś troche przećwiczyła, pętle for oraz pisanie ifów więc myślę ze może być to dość przyjemne zadanie

**Comment by Heraved** [comment]
finish
